### ISSUE TITLE
Rust CI builds should fail if Cargo.lock is outdated 

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#1012]
https://doc.rust-lang.org/cargo/commands/cargo-generate-lockfile.html#manifest-options

**Comment by mrinalwadhwa** [comment]
whatever the command is to check for this, will go here in gradle.
https://github.com/ockam-network/ockam/blob/develop/implementations/rust/build.gradle#L17

**Comment by gabhijit** [comment]
Is anyone working on this? I can send a PR for this. 

This looks fairly straight forward.

A small comment -  we could use either `--frozen` or `--locked` . When `--frozen` option is used, no network calls are made, which means if a dependency is not downloaded already in the cargo cache, the build fails even when the `Cargo.lock` file is up to date, which is a false negative. Best is to use `--locked`, as this is good enough to make sure that the `Cargo.lock` file is up  to date.

**Comment by mrinalwadhwa** [comment]
Hey @gabhijit 👋 
No, no one is looking at it, thank you for picking it up.

> Best is to use --locked, as this is good enough to make sure that the Cargo.lock file is up to date.
That sounds like the best option 👍

**Comment by gabhijit** [comment]
This issue can be closed now.

**Comment by mrinalwadhwa** [comment]
Thanks @gabhijit 🙏
