### ISSUE TITLE
Enable Clippy in CI

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#1014]
Now that everything is building in Docker we can enable clippy in CI
https://github.com/ockam-network/ockam/blob/develop/implementations/rust/build.gradle#L17

This will likely break the nightly build which is not run in docker but directly in the Github Hosted runners. We need a way to tackle that. I think its okay if the shortcut is not running the nightly matrix and only running it in docker for now. Having continuous clippy checks is much more useful.

https://github.com/ockam-network/ockam/blob/develop/.github/workflows/nightly.yml

**Comment by adrianbenavides** [comment]
Based on my experience, having the nightly clippy enabled as a mandatory step is a pain, as it will break the pipelines when new rules are applied, which happens very often.

I'd recommend having two different clippy steps:
1. mandatory without nightly
2. optional with nightly, to get ahead of upcoming (potential) changes

Although, if you haven't been enforcing clippy until now, I'd set the non-nightly step as optional as well until all clippy recommendations are applied, which could be done in small PR's.

**Comment by mrinalwadhwa** [comment]
That's great advice 👍 👍

**Comment by mrinalwadhwa** [comment]
Fixed in #1200
