### ISSUE TITLE
Rust CI builds should run cargo audit

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#1048]
The ockam crate currently fails `cargo audit`
https://github.com/RustSec/cargo-audit

```
» cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 263 security advisories (from /Users/mrinal/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (152 crate dependencies)
Crate:         generic-array
Version:       0.12.3
Title:         arr! macro erases lifetimes
Date:          2020-04-09
ID:            RUSTSEC-2020-0146
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0146
Solution:      Upgrade to >=0.8.4, <0.9.0 OR >=0.9.1, <0.10.0 OR >=0.10.1, <0.11.0 OR >=0.11.2, <0.12.0 OR >=0.12.4, <0.13.0 OR >=0.13.3
Dependency tree:
generic-array 0.12.3

Crate:         generic-array
Version:       0.13.2
Title:         arr! macro erases lifetimes
Date:          2020-04-09
ID:            RUSTSEC-2020-0146
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0146
Solution:      Upgrade to >=0.8.4, <0.9.0 OR >=0.9.1, <0.10.0 OR >=0.10.1, <0.11.0 OR >=0.11.2, <0.12.0 OR >=0.12.4, <0.13.0 OR >=0.13.3
Dependency tree:
generic-array 0.13.2

Crate:         failure
Version:       0.1.8
Warning:       unmaintained
Title:         failure is officially deprecated/unmaintained
Date:          2020-05-02
ID:            RUSTSEC-2020-0036
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree:
failure 0.1.8
└── bbs 0.4.1
    └── ockam 0.3.0

Crate:         pin-project-lite
Version:       0.2.4
Warning:       yanked
Dependency tree:
pin-project-lite 0.2.4
└── tokio 1.2.0
    └── ockam_node 0.3.0
        └── ockam 0.3.0

error: 2 vulnerabilities found!
warning: 2 allowed warnings found
```

**Comment by adrianbenavides** [comment]
Hi @mrinalwadhwa, the general idea here is adding the audit job in `.github/workflows/ci.yml` + adding the command in `build.gradle` right? 

Also, given that's already failing, would it be a good idea to set this step as [optional](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)?

And the last question, the `audit` tool should be added to the [docker image](https://github.com/ockam-network/ockam/blob/develop/tools/docker/builder/Dockerfile#L45) right?

**Comment by mrinalwadhwa** [comment]
Hey @adrianbenavides thanks for looking into it 🙏 

> the audit tool should be added to the docker image right?

Yes

> given that's already failing, would it be a good idea to set this step as optional?

That would be perfect.

> the general idea here is adding the audit job in .github/workflows/ci.yml

Yes

> adding the command in build.gradle right?

If you add it at [this list](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/build.gradle#L9) the ockam commands gradle plugin will add the tasks. In case you're curious how that works the plugin code is [here](https://github.com/ockam-network/ockam/blob/develop/tools/gradle/plugins/commands/src/main/groovy/network/ockam/gradle/commands/CommandsPlugin.groovy)

Thank you for spending time on this.

**Comment by mrinalwadhwa** [comment]
Also when you send a PR, could you also accept our CLA.

Read the CLA at
https://www.ockam.io/learn/how-to-guides/contributing/cla/

To accept the CLA please send a different PR to our contributors repo indicating that you accept the CLA by adding your Git/Github details in a row at the end of the CONTRIBUTORS.csv file:
https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv

Looking forward to merging your first contribution!!

**Comment by adrianbenavides** [comment]
Quick question: what's the process for updating the docker image? Do I have to create a separate PR just with the Dockerfile changes before using those changes in the cargo-audit PR?

**Comment by mrinalwadhwa** [comment]
Yes that's currently manual.. if you leave a PR for the dockerfile.. I'll merge and publish the image in my morning (pacific time)

**Comment by adrianbenavides** [comment]
Nice, thanks @mrinalwadhwa!

**Comment by adrianbenavides** [comment]
Any update on this? Did the docker image got updated? I have the MR enabling cargo audit ready to be published! :smile:

**Comment by adrianbenavides** [comment]
Any update on this @mrinalwadhwa? Did the docker image got updated? I have the MR enabling cargo audit ready to be published! :smile:

**Comment by mrinalwadhwa** [comment]
@adrianbenavides sorry for taking a few days to look into this. It turned out that even though `cargo-audit` was installed, `CARGO_HOME` didn't have the right permissions so it didn't succeed. 

I've published a new image and updated the CI workflow.

Looking forward to you PR enabling cargo audit.

**Comment by adrianbenavides** [comment]
@mrinalwadhwa  wow, I tried building and running the docker image in my local environment and I didn't catch that :facepalm: 

Thanks for your help!

**Comment by mrinalwadhwa** [comment]
Happy to help, we greatly appreciate the time you're spending on this 🙏 

With the latest build changes the best place to add cargo audit is this list of lint commands
https://github.com/ockam-network/ockam/blob/develop/implementations/rust/build.gradle#L28-L32 

Looking forward to your PR on that.
