### ISSUE TITLE
Elixir: intermittent crash on UDP aead_aes_gcm_encrypt

### ISSUE THREAD

**Issue by mjc** [ockam-network/ockam#1069]
This seems to be because of invalid input.

Output from a failing test is available from @mjc.

Definition of done: 

aead_aes_gcm_encrypt cannot get invalid input from UDP transport.

**Comment by feniks65** [comment]
@mjc 
Can you please share the output from the failing test?
Maybe I would be able to add a sanity check in `aead_aes_gcm_encrypt`.
