### ISSUE TITLE
Rust - WebSocket Transport

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#1130]
Similar to the TCP Transport but over WebSockets
https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_transport_tcp

https://github.com/ockam-network/ockam/blob/develop/documentation/concepts/transports.md
https://github.com/ockam-network/ockam/blob/develop/documentation/concepts/application-layer-routing.md

**Comment by adrianbenavides** [comment]
I've started working on this issue (mostly running the examples and watching the last community video), but I've seen that the tcp transport is going to be refactored (this week?) and it also has some todos/fixmes. Do you think I should wait until it gets refactored?

**Comment by mrinalwadhwa** [comment]
That's awesome!

The tcp changes,this week, are mostly API tweaks so please move forward without them.

**Comment by mrinalwadhwa** [comment]
Please don't hesitate to ask questions. @spacekookie may able to provide context/feedback as you make progress.

**Comment by adrianbenavides** [comment]
I'm still trying to figure out where to put each piece of the logic (the worker's architecture). I'll try to get something done by the end of this week. I'll get back with some questions if I get stuck, thanks @mrinalwadhwa!

**Comment by mrinalwadhwa** [comment]
Awesome, looking forward to it!

**Comment by jared-s** [comment]
Done!
