### ISSUE TITLE
Rust - Implement a higher level TCP registration and initialization process

### ISSUE THREAD

**Issue by jared-s** [ockam-network/ockam#1161]
Establishing a TCP connection to a peer currently requires a workflow [such as](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_examples/examples/step-4-client.rs#L11-L15):

```rust
// Create and register a connection
let router = TcpRouter::register(&ctx).await?;
let connection = tcp::start_tcp_worker(&ctx, remote_node.parse::<SocketAddr>().unwrap()).await?;
router.register(&connection).await?;
```

We would like to simplify this process as much as possible, ideally to a single call.

**Comment by jared-s** [comment]
@spacekookie another issue related to TCP refactors

**Comment by spacekookie** [comment]
We can probably close this issue now, since the TCP transport has been refactored.
