### ISSUE TITLE
Rust - Getting Started Documentation Updates

### ISSUE THREAD

**Issue by jjscheel** [ockam-network/ockam#1309]
Per my comments in [Discussion #1134, "Get help getting started"](https://github.com/ockam-network/ockam/discussions/1134#discussioncomment-641787), here are a list of basic changes I propose submitting as a single PR:

1. [00. Setup](https://github.com/ockam-network/ockam/tree/develop/documentation/guides/rust/get-started/00-setup): Remove link behind "get started".
2. [00. Setup](https://github.com/ockam-network/ockam/tree/develop/documentation/guides/rust/get-started/00-setup): Add information about prerequisite of gcc.
2. [00. Setup](https://github.com/ockam-network/ockam/tree/develop/documentation/guides/rust/get-started/00-setup): Add comment to verify that Cargo has been added to $PATH
3. ~~[01. Node](https://github.com/ockam-network/ockam/blob/develop/documentation/guides/rust/get-started/01-node): Add a link to Tokio.~~
4. [02. Worker](https://github.com/ockam-network/ockam/blob/develop/documentation/guides/rust/get-started/02-worker): Provide more explanation of "address".
5. [05. Secure Channel](https://github.com/ockam-network/ockam/blob/develop/documentation/guides/rust/get-started/05-secure-channel): Reference Cargo.toml file as to where to add new values for vault.
6. [05. Secure Channel](https://github.com/ockam-network/ockam/blob/develop/documentation/guides/rust/get-started/05-secure-channel): Add links to applicable previous examples.

Typos not mentioned in email:
- [00. Setup](https://github.com/ockam-network/ockam/tree/develop/documentation/guides/rust/get-started/00-setup): "We're crating a library..."  really isn't a typo but should be parenthetically explained as it looks like a mis-spelled "creating".
- [01. Node](https://github.com/ockam-network/ockam/blob/develop/documentation/guides/rust/get-started/01-node): "This will down various..." should be "This will download various..."

As this is my first community PR, coaching, advice, and/or jokes accepted.

**Comment by jjscheel** [comment]
I've made the changes locally and will gladly submit a PR.  @mrinalwadhwa, @mattgreg, are these ok in a single PR?

**Comment by mattgreg** [comment]
A single PR works great.

**Comment by mrinalwadhwa** [comment]
@jjscheel awesome! Single PR makes sense here.

I suggest leaving out 4. from your list above because linking out of the flow can be distracting ... we may instead come up with a references section somewhere.

**Comment by jjscheel** [comment]
@mrinalwadhwa, ack.  Struck it from the original comment for completeness.

**Comment by SanjoDeundiak** [comment]
Can we close this?

**Comment by jjscheel** [comment]
I'm good.

**Comment by mrinalwadhwa** [comment]
Thank you @jjscheel
