### ISSUE TITLE
Rust Hop using ockam::worker

### ISSUE THREAD

**Issue by skrapi** [ockam-network/ockam#1375]
I just went through the Get Started guide and to define a Hop, this is the recommended code:

``` rust
pub struct Hop;

#[ockam::worker]
impl Worker for Hop {
    type Context = Context;
    type Message = Any;

    /// This handle function takes any incoming message and forwards
    /// it to the next hop in its onward route
    async fn handle_message(&mut self, ctx: &mut Context, msg: Routed<Any>) -> Result<()> {
        println!("Address: {}, Received: {}", ctx.address(), msg);

        let mut msg = msg.into_transport_message();
        msg.onward_route.step()?;
        msg.return_route.modify().prepend(ctx.address());
        ctx.forward(msg).await
    }
}

```

It is also recommended that `ockam` is imported like this:
``` 
[dependencies]
ockam = { version = "0", features = ["ockam_transport_tcp", "ockam_vault"] }
```

This assumes that the latest release includes `ockam::worker`, but it doesn't because that was only recently added in #1220. For the examples to work, I had to use  `#[ockam::async_worker]`. Maybe adding a minimum version number to the Set Up part could  fix this issue in the future, since I am assuming the API is still being heavily developed.

**Comment by jared-s** [comment]
Hey @skrapi !

Thanks a lot for catching this, and thanks for going through the guides! I'm fixing this right now. The `ockam::worker` change will be released Monday.

**Comment by SanjoDeundiak** [comment]
@jared-s closing this?
