### ISSUE TITLE
signature_core: Upgrade heapless dependency to 0.7 

### ISSUE THREAD

**Issue by jared-s** [ockam-network/ockam#1426]
Currently the signature_core crate depends on `heapless` 0.6. Other parts of our stack use `heapless` 0.7. 

A few things have been renamed, and the upgrade is not seamless, though upgrading looks pretty straight forward.

Let's upgrade signature_core to the same version of `heapless` as the rest of the stack.

**Comment by psinghal20** [comment]
Hi @jared-s, I am a new contributor to the repo. I have beginner experience with Rust. I would love to take a stab at this issue if no one is already working on it.

**Comment by jared-s** [comment]
Hey @psinghal20, that would be great!  No one has started on it yet. Happy to work with you on this, please let me know if you need help!

**Comment by psinghal20** [comment]
Thanks! I will start poking into the codebase and let you know if I face any challenges.

**Comment by psinghal20** [comment]
Hi @jared-s, I have upgraded the lib to `0.7.1` version and wanted to test out my changes. The crate builds for me but when I tried building the whole project using the docker/builder I faced some issues.

I believe the gradle settings run the build command in `--locked` mode causing issues while updating the lib dependency. After removing the `locked` flag from the `implementations/rust/build.gradle`, I met with `Const generics being unstable` warning in the docker image. 

Can you let me know what would be the best way to test out my changes? Thanks! :slightly_smiling_face:

**Comment by jared-s** [comment]
Great @psinghal20! We do keep the `locked` flag on. Typically failures related to the lock files mean that a dependent crate just needs its lockfile updated via `cargo generate-lockfile` or `cargo build`.

In the case of `signature_core` I would expect the top level `ockam` crate to need an updated lockfile, as well as the `examples/rust/get_started` project. If you push up your branch to a fork, I can help check it out.

**Comment by jared-s** [comment]
I will need to check out the docker build issue separately. Locally, I test by using `./gradle test_rust` from the `ockam` project root. But our Dockerized build process should also work.

**Comment by psinghal20** [comment]
Hi @jared-s, I have raised a draft PR with my changes. I have generated the `cargo.lock` file for each of the crates you mentioned. Also, I found the reason why the docker builder was failing for me. The docker builder depends on Rust 1.49 whereas this change introduces const generics in our codebase. This means now the project requires Rust 1.51 or greater to build.

**Comment by jared-s** [comment]
That's a great find regarding Rust 1.49 to Rust 1.51. I'll create an issue to upgrade that.

**Comment by psinghal20** [comment]
@jared-s Found one more issue, the field `remote_static_public_key` in Struct `State` in the file `implementations/rust/ockam/ockam_key_exchange_xx/src/state.rs` is never read from which causes the build failure due to `#[deny(warnings)]` is enabled for the crate. When trying to run the tests for the Ockam crate, I had to remove this deny condition to build and test successfully.
