### ISSUE TITLE
signature_ps: out of bounds indexing in BlindSignature::to_bytes and BlindSignature::from_bytes

### ISSUE THREAD

**Issue by jared-s** [ockam-network/ockam#1435]
The `BlindSignature` struct uses a 96 byte signature (`Self::BYTES`). 

There are two instances of out of bound index operations, in [to_bytes](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/signature_ps/src/blind_signature.rs#L178) and [from_bytes](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/signature_ps/src/blind_signature.rs#L188) which read beyond 96 bytes.

Clippy reports this error. Screenshot attached
![clippy](https://user-images.githubusercontent.com/1097548/120035372-5ae5e880-bfb3-11eb-8ec9-3f2938a37c12.png)

**Comment by mrinalwadhwa** [comment]
@mikelodder7 would love your thoughts on this 🙏

**Comment by mikelodder7** [comment]
I caught this in my testing as well. The solution is easy to fix. Change line 128 from 96 to 128. I just tried to submit a PR but github is blocking me.

**Comment by mrinalwadhwa** [comment]
@mikelodder7 thank you, just cleaned up some permissions, try creating the PR, it should be like before now ... or you could also do a fork and pr.

**Comment by jared-s** [comment]
Thanks @mikelodder7 !
