### ISSUE TITLE
Long running action

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#1438]
This action ran for almost 6hrs, not sure why .. logging it here just in case we see it happen again

https://github.com/ockam-network/ockam/runs/2697605860

<img width="475" alt="Screen Shot 2021-05-28 at 7 29 42 PM" src="https://user-images.githubusercontent.com/159583/120055489-550bf980-bfeb-11eb-80b0-10d070c2a6a7.png">

**Comment by SanjoDeundiak** [comment]
I think it's due to #1627 . We don't experience it anymore, therefore closing the issue
