### ISSUE TITLE
Tests for ockam_hub

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#1451]
Currently ockam_hub application runs a few workers and provides an HTTP API to create kafka services, but it doesn't have any unit tests.

Some test coverage for Ockam.Hub.Service.Alias, Ockam.Hub.Service.Echo, Ockam.Hub.KafkaStreamHandler and Ockam.Hub.Web would be a good start for the test coverage.

**Comment by hairyhum** [comment]
Addressed in #1456
