### ISSUE TITLE
Create a software Vault implementation in Rust

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#149]
We would like Ockam implementation like higher level languages (like Elixir) to use Rust for the cryptographic building blocks. 

This would mean implementing all the functions in the C vault interface in Rust
https://github.com/ockam-network/ockam/blob/develop/implementations/c/include/ockam/vault.h

Between RustCrypto and Dalek Cryptography, I think we can find all the building blocks in pure Rust.
https://github.com/RustCrypto
https://github.com/dalek-cryptography

Our Elixir implementation already calls C via Rust so once there is a Rust only implementation it can easily switch to using that

**Comment by hollyfeld** [comment]
@mrinalwadhwa I'm going to start working on this task in the next few days. If there is anything else to add in the meantime, or any reason not to start please let me know. Thanks!

**Comment by mrinalwadhwa** [comment]
@hollyfeld that's awesome! Thank you for working on this!

Here are some notes that may be helpful along the way:

1. Rust only - it would be great if this implementation is Rust only and does not have any C dependencies. This way, at least, in the best case configuration we benefit from Rust's safety guarantees.
This rules our libs like [ring](https://github.com/briansmith/ring).

2. `no_std` - we also want this implementation to not depend on libstd, if possible.
https://rust-embedded.github.io/book/intro/no-std.html

3. I expect that this rust code will get called by higher level languages like Elixir as well as by C.
We also expect Rust code to have C dependencies.

4. Secrets - We want secrets to stay behind the vault interface and only be referenced by user code. This allows key's to remain in hardware (like TEEs, TPMs)  where possible. The design of this in the [C interface](https://github.com/ockam-network/ockam/blob/develop/implementations/c/include/ockam/vault.h) is still a work in progress.

2. I suspect that these are the crates that will give us the cryptographic building blocks we need. If you end up considering an alternative then please let me know:  

    Random
    https://github.com/rust-random
    https://rust-random.github.io/book/intro.html

     SHA256
     https://crates.io/crates/sha2

     HKD5_SHA256
    https://github.com/RustCrypto/KDFs

     P-256
     This seems to 
     https://crates.io/crates/p256
     https://github.com/RustCrypto/elliptic-curves

     Curve25519
     https://github.com/dalek-cryptography/curve25519-dalek

     ECDH
     https://github.com/dalek-cryptography/curve25519-dalek
     https://github.com/dalek-cryptography/x25519-dalek

     AES-GCM
     https://crates.io/crates/aes-gcm
     https://docs.rs/aes-gcm/0.5.0/aes_gcm/

**Comment by hollyfeld** [comment]
@mrinalwadhwa This all makes sense, thanks. I'll get setup and plan on creating a PR for review only after some initial implementation. That way we can course correct early on if needed.

I've been watching commits for awhile and have seen the progression of the C interfaces, so my conceptual understanding is in a decent place. The interfaces are looking better all the time. Nice work @robinbudd and @mtm0183!

**Comment by mrinalwadhwa** [comment]
Closing this, since we now have a Rust [software vault](https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault). Thank you @hollyfeld for the early exploration on this 🙏
