### ISSUE TITLE
Avoid WebSocket context borrowing

### ISSUE THREAD

**Issue by SanjoDeundiak** [ockam-network/ockam#1549]
WebSocket Transport borrows Context and stores it inside its structure, which makes it impossible to mutate that Context from outside. WebSocket should instead create its own Context where needed.
Corresponding change to TCP was introduced here https://github.com/ockam-network/ockam/pull/1516

**Comment by SanjoDeundiak** [comment]
Hey @adrianbenavides, are you interested in fixing this issue? That would be great

**Comment by adrianbenavides** [comment]
Yes, sure!
