### ISSUE TITLE
Add KeyId computation while importing secret in ockam_vault

### ISSUE THREAD

**Issue by SanjoDeundiak** [ockam-network/ockam#1570]
KeyId is an optional identifier of asymmetric key pair, used to refer to a key, for example during storage, it's computed by hashing public key.

[Currently](https://github.com/ockam-network/ockam/blob/21b47e742de04c439947e50a46b4e0870d15094a/implementations/rust/ockam/ockam_vault/src/secret_impl.rs#L82) key id computation is skipped while importing the secret in SoftwareVault, which differs from behaviour during key generation. To match that behaviour import should compute key id for BLS and Curve25519 keys.

Ideally, corresponding tests should be added.

---
_If you would like someone to help / mentor / pair program with you as you work on your first Ockam issue, please leave a comment on [this discussion.](https://github.com/ockam-network/ockam/discussions/1081)_

**Comment by devalain** [comment]
Hello,

I would like to give it a try.
I am not completely new to rust (1 year) but that would be the very first time I try to contribute to an open source projet.

**Comment by devalain** [comment]
Is the issue not closed for a reason ?

**Comment by mrinalwadhwa** [comment]
No reason, closing. Thank you 🙏
