### ISSUE TITLE
Upgrade Docker builder images to Rust 1.55

### ISSUE THREAD

**Issue by jared-s** [ockam-network/ockam#1636]
Rust 1.55 was just released. We should update our builder soon. [https://github.com/ockam-network/ockam/blob/develop/tools/docker/builder/Dockerfile](https://github.com/ockam-network/ockam/blob/develop/tools/docker/builder/Dockerfile)

**Comment by jared-s** [comment]
Already done

**Comment by mrinalwadhwa** [comment]
Haven't bumped rust yet, the new builder version just adds cargo deny.

**Comment by jared-s** [comment]
1.55 is now available
