### ISSUE TITLE
Like ngrok, but using Ockam

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#1762]
When https://github.com/ockam-network/ockam/pull/1756 lands, we will have TCP Transport Inlets and Outlets. 

With that, it should be possible to build an example that does what [ngrok](https://github.com/inconshreveable/ngrok) does but using Ockam. I think a simple version of this should be possible in ~100 lines of Rust code, would be a really nice demo of how simple this is with Ockam.

The End-to-End Encryption with Rust guide has most of the code needed to do this.
https://github.com/ockam-network/ockam/tree/develop/documentation/use-cases/end-to-end-encryption-with-rust#readme

---
_If you would like someone to help / mentor / pair program with you as you work on your first Ockam issue, please leave a comment on [this discussion.](https://github.com/ockam-network/ockam/discussions/1081)_

**Comment by Stupremee** [comment]
Hey 👋 
I always wanted to play around with ockam and now I used this project idea as an inspiration and made a small ngrok-like application. Should I open a PR that adds a new example project or how else should the example be integrated?

**Comment by mrinalwadhwa** [comment]
@Stupremee that's awesome! yes a PR that adds an example to this path would be perfect
https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_examples/example_projects

We can discuss a deeper integration from there.
