### ISSUE TITLE
Use `AsRef<str>` rather than `Into<String>` in `ockam_transport_tcp` if only a `&str` is needed.

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#1945]
In `ockam_transport_tcp`, many functions accept arguments generic over `Into<String>`, but don't need an owned String, only a &str / something that can be parsed.

These cases should be changed to use `AsRef<str>` instead.

For example: https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_transport_tcp/src/lib.rs#L50-L54, and then its callers in https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_transport_tcp/src/router/handle.rs, and their callers, etc.

(I think many of these should probably be using https://doc.rust-lang.org/nightly/std/net/trait.ToSocketAddrs.html instead, but that's something for another time)

**Comment by mrinalwadhwa** [comment]
Thank you for pointing that out, we should fix it.

**Comment by mattjperez** [comment]
My first open-source PR opened! 

@thomcc @mrinalwadhwa, thanks for the quick assists!

**Comment by mattjperez** [comment]
@mrinalwadhwa I think we can close this now.
