### ISSUE TITLE
Header files in implementations/c/lib directory

### ISSUE THREAD

**Issue by ercanersoy** [ockam-network/ockam#196]
I have found header files on implementations/c/lib directory. These are at wrong location?

https://github.com/ockam-network/ockam/tree/develop/implementations/c/lib/channel
https://github.com/ockam-network/ockam/tree/develop/implementations/c/lib/memory
https://github.com/ockam-network/ockam/tree/develop/implementations/c/lib/random
https://github.com/ockam-network/ockam/tree/develop/implementations/c/lib/transport
https://github.com/ockam-network/ockam/tree/develop/implementations/c/lib/vault

**Comment by mrinalwadhwa** [comment]
Hi @ercanersoy, thank you for opening he issue .. no that is intentional.

Could you share a bit more about what you're trying to do? Are you trying to build the code, if so, then are you using cmake or something else?

**Comment by ercanersoy** [comment]
I have not tried the code. Should the header files are at implementations/c/include directory?

https://github.com/ockam-network/ockam/tree/develop/implementations/c/include/ockam

**Comment by mrinalwadhwa** [comment]
the choice to keep headers within module folders is intentional, the recent updates to cmake build takes this further and moved the header from `include/ockam` into indivisual modules. This allows us to create modular dependencies.

I hope that answers your question, if not please reopen the issue.
