### ISSUE TITLE
Add PR branches from forks to CI

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#197]
PRs from a fork currently don't trigger the pipeline.

**Comment by vvv** [comment]
This information might be useful:

* [GitHub Actions improvements for fork and pull request workflows](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) — posted 4 weeks ago

  > Today GitHub Actions shipped a series of features designed to improve your workflows when working with PRs from repository forks.

* [Pull request events for forked repositories](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories)

  > When you create a pull request from a forked repository to the base repository, GitHub sends the `pull_request` event to the base repository and no pull request events occur on the forked repository.
  >
  > Workflows don't run on forked repositories by default. You must enable GitHub Actions in the **Actions** tab of the forked repository.

**Comment by mrinalwadhwa** [comment]
Thanks for the pointers, I'll check it out.

**Comment by mrinalwadhwa** [comment]
This works now, thank you @vvv for the early pointers 🙏
