### ISSUE TITLE
Use `AsRef<str>` rather than `Into<String>` in `ockam_transport_websocket` if only a `&str` is needed.

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#1970]
This is equivalent to https://github.com/ockam-network/ockam/issues/1945, but for `ockam_transport_websocket`. I haven't yet checked how many of these there are, but certainly there are a couple, such as https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_transport_websocket/src/lib.rs#L119

**Comment by fisherdarling** [comment]
I'll take this up!
