### ISSUE TITLE
Run action when workflow files are updated

### ISSUE THREAD

**Issue by metaclips** [ockam-network/ockam#1975]
Currently, GitHub Actions only run when crates or gradle files are updated e.g. https://github.com/ockam-network/ockam/blob/73ff992de50d59967baca88ce5fcfae22ae7a5a0/.github/workflows/rust_build_ockam_ockam_core.yml#L10-L14. 
We should also run workflow actions when workflow files are updated, for [example](https://github.com/ockam-network/ockam/commit/cbb6ecf4d2ebcc9809cb6e053540c258da16f60e)

**Comment by wkk** [comment]
Hi there. I believe I fixed `CommandsPlugin.groovy` but I'm struggling to regenerate the workflow files. Any advice?

**Comment by mrinalwadhwa** [comment]
@wkk thank you so much for the work you put into this.

With the recent change of us using Rust Cargo workspace .. we ended up removing the CommandPlugin completely in #2308 ... It made understanding what is going on the gradle build simpler.

Thank you for taking time to contribute 🙏
Let me know if you want to work on a different feature and I would be happy to help.
