### ISSUE TITLE
Fix TcpTransport lazy connection possibly breaking ordering guarantee

### ISSUE THREAD

**Issue by SanjoDeundiak** [ockam-network/ockam#1978]
Local delivery (between workers inside one node) and Tcp delivery are meant to guarantee message ordering, however, lazy connections can possibly break ordering. Basically, upon receiving first message for tcp address that we aren’t connected to, tcp router will initiate connection and requeue everything that is directed to this address until connection is established. Obviously, requeing messages can break ordering. Calling TcpTransport::connect before sending messages (as we were doing before) will guarantee ordering.
https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_transport_tcp/src/router/router.rs#L88

**Comment by SanjoDeundiak** [comment]
Possible fix is to delegate actual tcp connect from [WorkerPair](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_transport_tcp/src/workers/worker_pair.rs#L77) to ```TcpSendWorker::initialize``` or ```TcpRecvProcessor::initialize```, and make [connect](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_transport_tcp/src/router/router.rs#L95) call register new worker within tcp router immediately. This way since ```TcpSendWorker``` is already started and its address is known to tcp router, we can forward messages to it immediately (therefore, preserve ordering), even though actual tcp connection will be created after ```TcpSendWorker::initialize``` or ```TcpRecvProcessor::initialize``` is called.

**Comment by younes-io** [comment]
Hi @SanjoDeundiak,
Where can I find in the documentation the description of the Ockam transport TCP connection and message transmission?
