### ISSUE TITLE
Make TryAsyncClone trait derivable. Add TryAsyncClone impl for structs that implement Clone

### ISSUE THREAD

**Issue by SanjoDeundiak** [ockam-network/ockam#1998]
Provide macro that allows to derive ```AsyncTryClone``` trait like this
```rust
#[derive(AsyncTryClone)]
struct Foo {
   bar: Bar
}
```
This should work for structures for which all fields implement AsyncTryClone.
Additionally, every struct that implement Clone should automatically get AsyncTryClone impl.

**Comment by plaxi0s** [comment]
I did implement a proc macro for this [plaxi0s/async-try-clone-macro](https://github.com/plaxi0s/async-try-clone-macro/tree/master). About the second part, adding an impl like this might work.
```
#[async_trait]
impl<T: Clone + Sync> AsyncTryClone for T {
    async fn async_try_clone(&self) -> Result<Self, Error> {
        Ok(self.clone())
    }
}
```
