### ISSUE TITLE
Improve cmake setup

### ISSUE THREAD

**Issue by SanjoDeundiak** [ockam-network/ockam#201]
Currently cmake is only usable via command line and is not friendly, also CLion doesn't recognise such cmake setup and doesn't allow to seamlessly build&test project.

 Details:
1. Platform name is expected to be provided to cmake from command line, there should be a way to determine platform automatically (but it may be a good idea to keep ability to set it manually as well)
`
CMake Error at cmake/ockam_platform.cmake:59 (message):
  Unable to determine target platform!
`
2. Test targets are not recognised by CLion as possible execute targets, so you can only build libraries, but you cannot run tests
![Screenshot](https://user-images.githubusercontent.com/6513916/84926874-b1c11d80-b0d4-11ea-8f87-7ead07dc8c2b.png)

**Comment by mrinalwadhwa** [comment]
Thank you for filing this.

**Comment by robinbudd** [comment]
I expect the problem is in the CLion configuration, since it CMake-based. I use CLion and have no trouble building both libraries and tests. Here are the relevant options:
![image](https://user-images.githubusercontent.com/9142532/85317479-4b8d1f80-b473-11ea-8e5e-82565ce7c25f.png)
