### ISSUE TITLE
Rust build on macOS fails

### ISSUE THREAD

**Issue by SanjoDeundiak** [ockam-network/ockam#210]
Currently building rust project on macOS results in following error:
```
warning: LLVM_PREFIX was not set, and cannot find llvm-config, will not regenerate bindings
   Compiling ockam-vault-sys v0.7.0 (/---/ockam/implementations/rust/crates/ockam-vault-sys)
error: couldn't read /---/ockam/implementations/rust/target/debug/build/ockam-vault-sys-269f507587e26d20/out/bindings.rs: No such file or directory (os error 2)
 --> crates/ockam-vault-sys/src/bindings.rs:5:1
  |
5 | include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

The following warnings were emitted during compilation:

warning: LLVM_PREFIX was not set, and cannot find llvm-config, will not regenerate bindings

error: could not compile `ockam-vault-sys`.

To learn more, run the command again with --verbose.
```

**Comment by mrinalwadhwa** [comment]
Installing LLVM and setting LLVM_PREFIX in your local environment will fix this, however I think we can eliminate the need for this all together.

The `build.rs` file uses the LLVM_PREFIX to help `bindgen` generate the rust C bindings.

We're currently using bindgen as a library, but we could just update the bindings on the CLI
https://rust-lang.github.io/rust-bindgen/library-usage.html
https://rust-lang.github.io/rust-bindgen/command-line-usage.html

The stated reason for why someone may prefer bindgen as a lib is:
> Often times C and C++ headers will have platform- and architecture-specific #ifdefs that affect the shape of the Rust FFI bindings we need to create to interface Rust code with the outside world. By using bindgen as a library inside your build.rs, you can generate bindings for the current target on-the-fly. Otherwise, you would need to generate and maintain x86_64-unknown-linux-gnu-bindings.rs, x86_64-apple-darwin-bindings.rs, etc... separate bindings files for each of your supported targets, which can be a huge pain. The downside is that everyone building your crate also needs libclang available to run bindgen.

However we don't have ifdef's in our headers and using bindgen as a lib adds 50+ dependencies which we would prefer not to have.

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa it looks like I had installed llvm using homebrew, but adding "/usr/local/opt/llvm/bin" to PATH was also needed to make it work. Worth adding this to installation instructions somewhere?

**Comment by mrinalwadhwa** [comment]
this is fixed with the recent changes that no longer rely on bindgen
