### ISSUE TITLE
Refactor to move all `proc-macro`s into one crate

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#2186]
We currently have 5 different `proc-macro` crates

From [rust docs](https://doc.rust-lang.org/reference/procedural-macros.html#procedural-macros), I see that:
> Procedural macros must be defined in a crate with the crate type of proc-macro.

I'm curious if they need to be in separate crates

https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_node_attribute
https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_node_test_attribute
https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_message_derive
https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_macro
https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_test_attribute

**Comment by thomcc** [comment]
Huh, I thought these already *were* in the same crate. I think *at most* we probably just want 2, one for tests, and one not for tests.

**Comment by mrinalwadhwa** [comment]
Great! we can do some refactoring and remove the unnecessary crates 👍 
Could they all be in the same crate with the testing macros behind a feature flag?

**Comment by thomcc** [comment]
I don't think we should merge ones that are for internal-only testing (even behind a flag), and I think moving forward having a place to put internal-only test macros will be useful. That isn't a crate we need/want to publish though.

While I don't think this is difficult, and a contributor should do it, given the struggle we just had around the `ockam_macro` crate's release (and dependency cycles), I think I'll take this, and use it to merge everything other than vault_test_attribute.

**Comment by adrianbenavides** [comment]
The `node_test_attribute` should be a drop-in replacement of the `node_attribute`, so this is roughly what should be done:
- delete the `node_attribute` crate
- rename the `node_test_attribute` 
- change the usages of the `node_test_attribute::node_test` in some tests
- probably the `node_test` macro should be compiled for test code only (maybe out of the scope for this issue) 

@thomcc @SanjoDeundiak let me know if I can help with this or if you'll do this as part of this issue.

**Comment by adrianbenavides** [comment]
> I haven't started on this yet (and won't be able to start until later today) — if you wanted to take it (and replace the node macro at the same time) that'd be fine, since I believe you wrote most of these macros.

I can try this tomorrow. 

> 2. move all macros only used in tests to a macro specifically for tests — specifically I was just going to rename ockam_vault_attribute crate. This can be done later.

Just to clarify, you mean "_move all macros only used in tests to a **crate** specifically for tests_" right?

**Comment by thomcc** [comment]
> I can try this tomorrow.

All yours!

> Just to clarify, you mean "_move all macros only used in tests to a **crate** specifically for tests_" right?

Erm, yes 😅

**Comment by jared-s** [comment]
Awesome, this also crossed my mind during release yesterday. Consolidation would be great

**Comment by thomcc** [comment]
This is done.
