### ISSUE TITLE
Same dependencies in dependencies and dev-dependencies?

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#2187]
The `ockam` crate has a couple of repeating dependencies in the dependencies and dev-dependencies sections, is this necessary / helpful in some way?

`ockam_vault_sync_core` && `ockam_key_exchange_xx`

https://github.com/ockam-network/ockam/blob/53a056be8e453329c0ddbd6b3881d6168c18c65e/implementations/rust/ockam/ockam/Cargo.toml#L75-L106

**Comment by thomcc** [comment]
Yes, because it's non-optional as a dev dependency, and it enables different features in that list.

**Comment by thomcc** [comment]
I'm going to close since this is fine. If you'd like I can try and move the tests elsewhere which would simplify things.
