### ISSUE TITLE
Renumber WebSocket transport type from 2 to 3

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#2194]
In `ockam_transport_websocket`, the Rust code declares the address type for WebSocket to 2: https://github.com/ockam-network/ockam/blob/ba324e9d30ed35b04a804fcdf802207d59477ba3/implementations/rust/ockam/ockam_transport_websocket/src/lib.rs#L91-L92

However, in the elixir implementation, 2 is used for UDP: https://github.com/ockam-network/ockam/blob/ba324e9d30ed35b04a804fcdf802207d59477ba3/implementations/elixir/ockam/ockam/lib/ockam/transport/udp/address.ex#L8-L9

We should change the Rust to use 3 (or some other number) for websockets (and consider how we can avoid this sort of problem in the future).

**Comment by mrinalwadhwa** [comment]
Let's use 3 for Websocket 👍
