### ISSUE TITLE
Add `rust-version` to each `Cargo.toml`

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#2204]
[`rust-version` in Cargo.toml](https://github.com/rust-lang/rust/issues/65262) support landed in 1.56, so we should consider putting it in all of our Cargo.toml. I think 1.56 is also the version we support, so it would look like a `rust-version = "1.56.0"` line in them.

(If we actually support an older version, it doesn't break, but they get a warning)

**Comment by totsteps** [comment]
@thomcc can you assign this to me as well?
