### ISSUE TITLE
CI for Rust crates using workspace feature

### ISSUE THREAD

**Issue by metaclips** [ockam-network/ockam#2230]
With `workspace feature`, we can reduce our workflows to a single GitHub Action that can `check our rust crates` and also `perform feature check` for individual crates.
This would also alleviate the need to run Gradle for every new crate created in /ockam repo.

**Comment by thomcc** [comment]
As of #2243, we're completely good by clippy's standards, so it would be nice to start that check.

**Comment by mrinalwadhwa** [comment]
It's work in progress but - I started this in https://github.com/ockam-network/ockam/pull/2308

**Comment by metaclips** [comment]
Fixed in https://github.com/ockam-network/ockam/pull/2308 thanks @mrinalwadhwa
