### ISSUE TITLE
Delete the `ockam_node_no_std` crate.

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#2287]
The [`ockam_node_no_std`](https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_node_no_std) crate was mostly around to remind us that we needed to support no_std and alternative nodes. The support for no_std landed in ockam_node and ockam_executor, and the alternative node work is actively being worked on, but won't involve this crate.

As a result, this crate should just be removed. Note that you should also delete some references to it from elsewhere, so you may need to do a search. For example, inside CI (`.github/workflows`), in any Cargo.toml files of other crates, etc.

**Comment by totsteps** [comment]
@thomcc can I help with this?

**Comment by mrinalwadhwa** [comment]
@totsteps 👋  yes of course! assigning this to you.
Let us know if you have any questions as you make the change.
