### ISSUE TITLE
Move the `ockam_vault_core` create into `ockam_core`.

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#2288]
We're trying to reduce the number of crates, and part of that is moving `ockam_vault_core` into a new `vault` submodule of `ockam_core`. I think this basically looks like

1. Make a new `pub mod vault;` in [`ockam_core`](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_core/src/lib.rs).
    - Note: unlike the [other modules](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_core/src/lib.rs#L54-L60), I think we shouldn't `pub use vault::*` from the root here, since we'd like to move away from this.

2. Move the code from `ockam_vault_core/src/*` to a new `ockam_core/src/vault/*` directory (and updating anything necessary, renaming lib.rs to mod.rs, renaming any references that were previously `crate::Something` to be `crate::vault::Something`)

3. Update the [doc comments](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_vault_core/src/lib.rs#L3) so that it says "this module" rather than "this crate" and such. (Ask if you need help wording this).

4. Change uses of `ockam_vault_core::Foo` to use `ockam_core::vault::Foo` across our crates.

5. Delete the `ockam_vault_core` crate, and any references to it (be sure to check `.github/workflows`, and to do a search for `ockam_vault_core`).

That's the basic idea anyway (I may have missed something). Feel free to ask questions if anything is unclear.

**Comment by totsteps** [comment]
@thomcc can I help with this?

**Comment by mrinalwadhwa** [comment]
@totsteps 👋  yes of course! Thank you for picking it up. Assigning this to you.
Let us know if you have any questions as you make the change.

**Comment by mrinalwadhwa** [comment]
Fixed om #2339
