### ISSUE TITLE
Releases for Windows are throwing errors on build 0.2.7

### ISSUE THREAD

**Issue by caleteeter** [ockam-network/ockam#23]
If you have a question, please don’t file an issue, instead, ask the [Ockam team on Slack](https://join.slack.com/t/ockam-community/shared_invite/enQtNDk5Nzk2NDA2NDcxLWMzMzJlZjQzOTZjYWY0YmNkNWE1NmI1M2YyYzlkNjk4NDYyYzU0OWE0YTI4ZjcwNDBjNmQ4NzZjZTMzYmY3NDA)

## Expected Behavior
When running the Ockam client for windows (both i386 and x64 releases), in version 0.2.7, the client should register a new DID when calling: `ockam register <alias>`.

## Actual Behavior
The client looks to be registering ok, but the persistance back to disk shows some errors.

![image](https://user-images.githubusercontent.com/8452367/52138469-38c64080-261b-11e9-8a20-e2690f781b4a.png)

## Steps to Reproduce the Problem

	1. Download the 0.2.7 release for windows (x386 or x64)
	2. Extract the release and run the client (ockam) from a command prompt

## Environment

- Ockam Version: 0.2.7
- Operating System:  Windows 10 (version 1809)

**Comment by mrinalwadhwa** [comment]
Thanks @caleteeter, my first guess is Windows doesn't like some of the chars in the DID file name, we should escape them.

**Comment by mrinalwadhwa** [comment]
@caleteeter so the fix would go here:
https://github.com/ockam-network/ockam/blob/master/cmd/ockam/entity.go#L63
maybe we replace the colon with an underscore.

If you want to take it up, this is a good first issue to get familiar with the build + pr process that is described in the contribution guild.

Let me know.

**Comment by caleteeter** [comment]
On it.

**Comment by hirako2000** [comment]
Is the issue not in the `did` package, @mrinalwadhwa ?
https://github.com/ockam-network/did/blob/master/did.go#L55

**Comment by mrinalwadhwa** [comment]
@hirako2000 since `did` is a standard, we want `did` package's `String` function to return the standard format .. however when we store that to a file in the `ockam` command, we can replace the colon with something else to fix this bug.
