### ISSUE TITLE
Fix warning in contact.rs

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#2333]
warning: unresolved link to `KeyAttributes`
   --> implementations/rust/ockam/ockam_entity/src/contact.rs:108:69
    |
108 |     /// Get [`PublicKey`]. Key is uniquely identified by label in [`KeyAttributes`]
    |                                                                     ^^^^^^^^^^^^^ no item named `KeyAttributes` in scope
    |
    = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

**Comment by jared-s** [comment]
Fixed in #2337
