### ISSUE TITLE
Documentation bug 

### ISSUE THREAD

**Issue by yorkerhodes3** [ockam-network/ockam#235]
There is a broken link in this text at the bottom: 

documentation/concepts/secure_channels.md

Decoupling the secure channel protocol from the transport protocols removes the complexity of dealing with multiple disparate secure protocols, enables us to have end-to-end secure channels, minimizes the attack surface and helps us to build better end-to-end secure and private systems.

The precise design of the secure channel protocol is being discussed as part of **Ockam Proposal OP-0002.**

**Comment by mrinalwadhwa** [comment]
thanks for reporting it @yorkerhodes3

**Comment by vvv** [comment]
> There is a broken link in this text at the bottom:
> documentation/concepts/secure_channels.md

The link at the bottom of [`documentation/concepts/secure_channels.md`](https://github.com/ockam-network/ockam/blob/400d0e80f025f459a27c4da28a717f7d7fbae47a/documentation/concepts/secure_channels.md) is valid.  Still, this issue prompted me to check all links to OP-* documents and find that some of them are genuinely broken; see #366.  Thanks to @yorkerhodes3!

I guess this issue can be closed.

**Comment by vvv** [comment]
@mrinalwadhwa It looks like cla-bot is misconfigured: it barks at those who want to submit bug reports, requesting them to sign CLA.  Shouldn't cla-bot mind pull requests only?

![cla-bot message](https://user-images.githubusercontent.com/17462/91647089-2f06f800-ea5f-11ea-8449-2d40bb77db8d.png)

**Comment by mrinalwadhwa** [comment]
that was intentional, if someone contributes ideas or code in an issue description we would like their formal permission before we use them.

**Comment by mrinalwadhwa** [comment]
fixed in #366
