### ISSUE TITLE
Change `no_main` feature on `ockam_macros` to an argument

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#2358]
Right now if [`no_main`](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_macros/Cargo.toml#L21-L24) is enabled on ockam_macros, it changes how the `ockam::node` macro is expanded.

However, it's reasonable for someone to have this enabled on one instance of the macro in a workspace, and not another, so we should change it to an argument rather than a feature. That is, I'm imagining something like `#[ockam::node(no_main)]`.

This doesn't require much ockam-specific experience, so I've marked it as "good first issue", but it probably does require familiarity with syn/proc macros.

**Comment by pro465** [comment]
@thomcc done!

now we need to document the support for `no_main` in `ockam::node`.
