### ISSUE TITLE
Upgrade CMake

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#241]
- [x] channel
- [x] channel/tests
- [x] codec
- [x] codec/tests
- [x] error
- [x] io
- [x] key_agreement
- [x] key_agreement/xx
- [x] key_agreement/xx/tests
- [x] log
- [x] log/log
- [x] memory
- [x] memory/stdlib
- [x] memory/stdlib/tests
- [x] mutex
- [x] mutex/pthread
- [x] queue
- [x] queue/pthread
- [x] queue/pthread/tests
- [x] random
- [x] random/urandom
- [ ] router
- [x] transport
- [x] transport/posix_socket
- [x] transport/posix_socket/tests
- [x] vault
- [x] vault/tests
- [x] vault/default
- [x] vault/default/tests
- [x] vault/atecc608a
- [x] vault/atecc608a/tests
- [ ] vault/atecc508a
- [ ] vault/atecc508a/tests
- [x] external/bearssl
- [x] external/cmocka
- [x] external/cryptoauthlib

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa only 3 modules are left:
- [ ] router
- [ ] vault/atecc508a
- [ ] vault/atecc508a/tests
 All of them are unimplemented, so maybe it's time to close this issue
