### ISSUE TITLE
Improve Logging in C

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#243]
- [x] deal with multiple log modules
- [x] figure out the interface we should expose as `ockam/log.h`
- [x] figure out how the logger will be chosen - CMake?
- [x] figure out how logging will be used.
- [x] how does this affect log/CMakeLists.txt
- [ ] how does logging work with C and Rust together

**Comment by mrinalwadhwa** [comment]
@SanjoDeundiak proposal 
https://github.com/SanjoDeundiak/cmake-test1
https://github.com/SanjoDeundiak/cmake-test2

**Comment by SanjoDeundiak** [comment]
C <-> Rust log interference should be discussed, other items should be resolved by merging #289
