### ISSUE TITLE
Ockam protocol composition and encoding design

### ISSUE THREAD

**Issue by spacekookie** [ockam-network/ockam#2450]
The current design of pipe and channel workers is via interior composition, to avoid the memory and resource burden of spawning more workers.

However this comes with different problems. The current approach relies on implicitly shared state and interactions between different behaviour handlers that may not scale to build complicated protocols.

As part of this issue we aim to build different prototypes to tackle this design problem.

This is also related to the way that Ockam protocols can exchange metadata between different workers in the system. 

- Relevant PR #2453
- Relevant roadmap #2458

## Worker composition outline

- A worker MUST be able to setup additional behaviours
- Each behaviour MUST to be able to define inputs and outputs
- A behaviour MAY provide scope metadata via a metadata message abstraction
- Expose the setup mechanisms via Rust API

## Message metadata

See design outline on Miro board and https://github.com/ockam-network/proposals/pull/87

Initial API implementation available on #2453

**Comment by spacekookie** [comment]
# Workers & System Handlers design

In Ockam a "Worker" is an asynchronously scheduled entity with its own
mailbox, a set of addresses, and routing infrastructure. A "Worker
System" is a single Worker which has been setup to handle different
message types via detached state. These message handlers are called
"System Handlers".

This section outlines the design philosophy behind this distinction,
and when a component is more suitable to be a Worker or a System
Handler.


## Reasoning

The main driving factor behind this design framework is resource
consumption on low-power hardware.  Ockam already has a mechanism
through which composable behaviours are possible, called Workers, and
message passing between their addresses.  The problem is that this
creates overhead on embedded systems, a market that we want to target
further in the future.


## Policy vs Mechanism

When designing this system it is useful to consider a design
philosophy used in the Linux kernel (among other places).

A **Mechanism** is a part of a larger system which enables the caller to
perform a certain function.  This could be simple things like sending
a message, or slightly more complicated things like verifying the
source of origin address on an incoming message.

**Policy** is the decision making structure that is used to define
what mechanisms are used, when, and how.  A mechanism by itself can
and must not make a complex decision.  It is the policy that encodes
how behaviours are used.


## Workers vs System Handlers

In this framework a **System Handler** is a **Mechanism**, while a
**Worker** is in the relm of **Policy**.

That means in places where behaviour can be encoded as a simple
function, with minimal state, and without needing to consider a lot of
other factors, this should be implemented as a **System Handler**.

On the other hand, a system that needs to interact with a lot of other
systems, make complex decisions based on authorisation, or the way it
was initialised **must** be implemented as a **Worker**.

Workers can then in turn compose additional behaviours as part of
System Handlers.

This way we achieve a composable architecture with a reasonable
separation of concerns.


## Example

Taking the current Pipe behaviour system and mapping it to this
language might make clear how it can be used.

* Pipe Sender - Worker
* Pipe Receiver - Worker
* Sender Confirmation - System Handler
* Receiver Confirmation - System Handler
* Receiver Ordering - System Handler

Implementing a simple channel on top of this architecture would simply
initialise two pipes with the correct system handlers (similar to how
insecure channels work currently).


## Alternatives

The alternative to this design choice would be investing heavily into
the optimisation of the underlynig runtime (both Ockam Node _and_ the
future's abstractions we use) so that we can use external worker
composition instead of having to implement internal composition types.


## Future work

One aspect to explore would be to break down the Secure Channel
crate into Mechanism and Policy.

**Comment by antoinevg** [comment]
So, let me see if I have this right… 

1. Everything is still a worker.
1. Whether a given set of workers use, for example, static dispatch vs. channel dispatch is a policy decision.
1. Policy decisions are implemented via System Handlers.

Which means that:

1. Communication between workers on e.g. a tiny PIC32 chip with 4K RAM that don't need the all singing, all dancing troupe of monkey dispatchers can simply implement the System Handlers as static function calls.
1. Most workers running in a server environment will use our existing collection of channels etc. via the same set of System Handlers.
1. For communication between workers with i9 CPU's and 1 TB RAM that are sitting on opposite sides of 10Gbps pipes we can implement those same System Handlers as a mixture of DMA and SPARTAN-6 FPGA cards. 

Is this more or less it?

**Comment by spacekookie** [comment]
> So, let me see if I have this right…
> 
>   1.  Everything is still a worker.
>    1. Whether a given set of workers use, for example, static dispatch vs. channel dispatch is a policy decision.
>    1. Policy decisions are implemented via System Handlers.

Yes, basically. For high-throughput systems with a lot of memory we _could_ map one System Handler per Worker and then use channel dispatch to communicate between these workers, similarly as to how the Elixir implementation handles this. But tbh I don't see this being a very important use case for the moment.

> Communication between workers on e.g. a tiny PIC32 chip with 4K RAM that don't need the all singing, all dancing troupe of monkey dispatchers can simply implement the System Handlers as static function calls.

A System Handler is still a _dynamic dispatch_ mechanism (using our good friend ` Box<dyn SystemHandler<_>>`). Actually I assume this works on `no_std` systems because we have `ockam_core::compat::boxed::Box`?)  Anyway, it does remove some layers of separation since a message no longer has to flow through the node router + worker mailbox.

**Comment by antoinevg** [comment]
> Actually I assume this works on no_std systems because we have ockam_core::compat::boxed::Box?)

Yup, dyn works fine with alloc's Box.
