### ISSUE TITLE
`crate-bump.sh` script uses bash features not supported in stock macOS.

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#2463]
By default, macOS comes with a rather old installation of `bash`:

```sh
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

This version doesn't seem to support `declare -A` which we use in `tools/scripts/release/crate-bump.sh`. Instead, I get an error like the following:

```sh
tools/scripts/release/crate-bump.sh: line 19: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

After this, it appears to work (I guess this version of bash does support associative arrays, but just doesn't support the `declare -A` flag), so I suspect we can just delete that line? Not sure.

CC @metaclips

**Comment by metaclips** [comment]
We declare hash table for faster lookup of crates to be bumped `with a different version` in crate-bump.sh and also to track `crates not be published` in crate-publish.sh. Can we use an updated version of bash? I use z shell and iTerm.

**Comment by thomcc** [comment]
Hash tables / associative arrays seem to work in the version of bash I have, but `declare -A` doesn't. Explicitly requiring zsh would probably be fine too — The version of `zsh` bundled with macOS is much newer.

Requiring a specific bash version is fine in principal, but updating the stock macOS version is usually somewhat dubious (although appears to be supported here), and we should include a version check if we want to go that route.

Is `declare -A` actually required here? I somewhat suspect it doesn't do anything.

**Comment by metaclips** [comment]
Associative arrays are supported in ^Bash 4. More [here](https://stackoverflow.com/questions/1494178/how-to-define-hash-tables-in-bash) and [here](https://www.oreilly.com/library/view/shell-scripting-expert/9781118166321/c09-anchor-3.xhtml)

**Comment by thomcc** [comment]
Hmm, as mentioned, the script still worked despite this.

**Comment by metaclips** [comment]
Yes, due to us not making a modified release. If we were to indicate a crate with a different version say Ockam Entity crate as a major release
`MODIFIED_RELEASE="ockam_entity:major" RELEASE_VERSION=minor tools/scripts/release/crate-bump.sh`
ockam_entity will be bumped as `minor` as it'll fail to lookup the hash table https://github.com/ockam-network/ockam/blob/b7a83237b2ee49e54208c4f945f031ee9609c95e/tools/scripts/release/crate-bump.sh#L33
We should indicate that the script be used in a bash version 4+. What do you think?

**Comment by thomcc** [comment]
Ah, that makes sense, thanks for explaining it to me (I'll admit, I hadn't looked closely at the code, nor are hashtables part of the bash featureset I'm used to).

Indicate how? Failing with an error is fine. And I guess just documenting it is fine if #2464 is addressed.

**Comment by metaclips** [comment]
Yup should do
