### ISSUE TITLE
Remove the "dev bump" part of the release workflow (e.g. don't use `-dev` versions in between publishes)

### ISSUE THREAD

**Issue by thomcc** [ockam-network/ockam#2466]
We've adopted a dev-bump workflow after releasing, meaning we bump all our crates to -dev versions after the release. There are a lot of downsides to this in Rust development — for example, it breaks `cargo`'s `[patch.crates-io]` feature.

I argued heavily (and convincingly enough for them to follow) to change the default behavior of this in cargo-release, because of these downsides — see my comments in this thread, starting at https://github.com/crate-ci/cargo-release/issues/82#issuecomment-933100970 for my arguments. So, as you can imagine, I don't think we should do it here.

It also makes our rebases more difficult, although we already have a problem here regardless of this.

**Comment by metaclips** [comment]
Haaa, nice. Fully in support!

**Comment by thomcc** [comment]
I've deliberately not performed the "dev bump" as part of the v0.45 release today (<https://github.com/ockam-network/ockam/releases/tag/ockam_v0.45.0>).

Assuming that's fine, this issue mostly tracks removing the documentation and scripting for it.
