### ISSUE TITLE
Fix error in `ockam_transport_tcp` docs

### ISSUE THREAD

**Issue by adrianbenavides** [ockam-network/ockam#2630]
The following lines should be deleted, as there is no `bind` method in the `TcpRouter` struct:

https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_transport_tcp/src/router/mod.rs#L206-L207

**Comment by antoinevg** [comment]
The crate layout has changed quite a lot so I've also committed a fix for this in the antoinevg/ga_review_ockam_transport_tcp branch
