### ISSUE TITLE
Driver for Universal Resolver

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#31]
https://github.com/decentralized-identity/universal-resolver

https://medium.com/decentralized-identity/a-universal-resolver-for-self-sovereign-identifiers-48e6b4a5cc3c

https://github.com/decentralized-identity/universal-resolver/blob/master/docs/design-goals.md

https://github.com/decentralized-identity/universal-resolver/blob/master/docs/architecture-drivers.md

https://github.com/decentralized-identity/universal-resolver/blob/master/docs/api-definition.md

**Comment by mrinalwadhwa** [comment]
The drivers are implemented as docker containers.

**Comment by carlosflrs** [comment]
https://github.com/decentralized-identity/universal-resolver/blob/master/docs/driver-development.md
