### ISSUE TITLE
CMake fails to fetch, configure cmocka

### ISSUE THREAD

**Issue by robinbudd** [ockam-network/ockam#330]
Verify that CMocka is not installed on your system (check /usr/local/lib/cmake/cmocka). When generating build files, CMake fails with the following error:
"CMake Error at external/cmocka/CMakeLists.txt:6 (find_package):
  By not providing "Findcmocka.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "cmocka", but
  CMake did not find one.

  Could not find a package configuration file provided by "cmocka" (requested
  version 1.1.5) with any of the following names:

    cmockaConfig.cmake
    cmocka-config.cmake

  Add the installation prefix of "cmocka" to CMAKE_PREFIX_PATH or set
  "cmocka_DIR" to a directory containing one of the above files.  If "cmocka"
  provides a separate development package or SDK, be sure it has been
  installed."

**Comment by mrinalwadhwa** [comment]
@robinbudd please run this on on your machine and post the output
```
cmake -S . -B testbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug --trace-source=external/cmocka/CMakeLists.txt
```

**Comment by robinbudd** [comment]
Resolved by uninstalling local cmocka
