### ISSUE TITLE
Elixir Vault NIF api

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#375]
It's idiomatic in Elixir to return `{:ok, return_value}` or `{:error, reason}` tuples from functions.

```
vault = Ockam.Vault.Software.default_init()
```

would better if it instead return `{:ok, vault}` or `{:error, reason}`

**Comment by niklaslong** [comment]
Seems like this has been resolved (not only for this function but the whole API): 
- [Elixir](https://github.com/ockam-network/ockam/blob/7fe37a3e9ac920b2f928bdecf5d750d31808eda8/implementations/elixir/ockam/ockam_vault_software/test/vault_software_test.exs#L19)
- [C](https://github.com/ockam-network/ockam/blob/7fe37a3e9ac920b2f928bdecf5d750d31808eda8/implementations/elixir/ockam/ockam_vault_software/native/vault/software/common.c#L17)

**Comment by mrinalwadhwa** [comment]
Yes it is. Thank you @niklaslong 🙏 
Helping close these is a great way to contribute

**Comment by SanjoDeundiak** [comment]
#676
