### ISSUE TITLE
Structure of Rust Modules / Crates

### ISSUE THREAD

**Issue by mikelodder7** [ockam-network/ockam#381]
- Core (`ockam` crate) (user api trats)
- Environment Independent (minimum functionality) (where should this live?)
- Environment specific (individual crates)

Guiding principle is Dependency Inversion.

[Google Doc](https://docs.google.com/document/d/1SIBYMAMALXscK6biLsJdLzqccfPWOi0AmVYNQxZXcdI/edit?usp=sharing) proposal

**Comment by mrinalwadhwa** [comment]
I think the "Environment Independent (minimum functionality)" should also live in the `ockam` crate.
