### ISSUE TITLE
Generalize Authentication

### ISSUE THREAD

**Issue by malnick** [ockam-network/ockam#42]
@mrinalwadhwa to add more notes.

**Comment by mrinalwadhwa** [comment]
subtask: https://github.com/ockam-network/ockam/issues/24

**Comment by mrinalwadhwa** [comment]
TODOs:
1. We need a primitive that bundles key generation, signatures and encryption into one compatible package.
2. Authentication Server (peripheral)
3. Authentication Client (central)
4. We need a mechanism to plugin transports into Authentication Server & Client
5. Transports can be different for Discovery of DID, Authentication and actual communication
6. The token/capability that is exchanged after Authentication may have specific cryptographic requirements, how do we handle that?

**Comment by malnick** [comment]
Added as #44 #45 #46 #47
