### ISSUE TITLE
Make SecretKeyContext extendable for outside of project Vault implementations

### ISSUE THREAD

**Issue by SanjoDeundiak** [ockam-network/ockam#465]
Part of #463 

Currently SecretKeyContext is enum which makes writing own Vault implementation impossible without changing Ockam code.
One of possible solutions: make SecretKeyContext empty trait (marker) to allow everybody roll out their own implementations. Our own software Vault implementation can still implement this trait as enum

**Comment by SanjoDeundiak** [comment]
@mikelodder7 another possible solution: associated type
https://gist.github.com/SanjoDeundiak/9079a0e837292598ed87ce5eac94c9e7

**Comment by mikelodder7** [comment]
I like the empty trait (marker) solution better. Thanks for this.
