### ISSUE TITLE
(Rust) CLI to demonstrate enrollment, at minimum to decide and document the set of commands that provide an example

### ISSUE THREAD

**Issue by nilslice** [ockam-network/ockam#492]

**Comment by nilslice** [comment]
@mrinalwadhwa - do you have everything needed for this?

**Comment by mikelodder7** [comment]
The first idea is to just use the `role` flag you already are using to enable the three non-mutually exclusive participant hats for enrollment

For example: `role=initiator,service`, `role=responder,enroller`, `role=initiator,enrollee`
