### ISSUE TITLE
(Elixir / NIF) use the `FilesystemVault` from Elixir

### ISSUE THREAD

**Issue by nilslice** [ockam-network/ockam#498]
@mikelodder7 / @mrinalwadhwa -- is this also used for the key exchange? 

Acceptance Criteria:
- make usable in the Elixir key exchange
- determine if the Rust kex should be used as NIF. @mikelodder7 can add context, but likely should use the Elixir kex.

+ Move the FilesystemVault module into the vaults crate

**Comment by nilslice** [comment]
@SanjoDeundiak - could you pick up after #584 is merged, and expose this to Elixir through a NIF?

**Comment by SanjoDeundiak** [comment]
@nilslice does it have higher priority then running atecc demo? I thought Mike is doing this nif

**Comment by nilslice** [comment]
@SanjoDeundiak, you're right - sorry about that. @mikelodder7, can you keep this moving?
