### ISSUE TITLE
the cla-action sometimes hangs forever

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#526]
![Screen Shot 2020-10-21 at 1 39 40 PM](https://user-images.githubusercontent.com/159583/96784931-f4587680-13a2-11eb-84c4-c4b33ec5cac8.png)

**Comment by mrinalwadhwa** [comment]
This pr cla-check never succeeded
https://github.com/ockam-network/ockam/pull/524

**Comment by SanjoDeundiak** [comment]
Haven't noticed that problem for some time
