### ISSUE TITLE
Multiple rust builds in CI 

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#527]
the rust build takes about 2+ mins to run
it is currently being invoked twice in CI
which accounts for 4+ mins from our total of 5 mins long CI ...

we should see if we can build rust once or parallelize

https://github.com/ockam-network/ockam/runs/1288941319?check_suite_focus=true

**Comment by nilslice** [comment]
![image](https://user-images.githubusercontent.com/7517515/96792355-76529a80-13b7-11eb-816c-ee4e8d07dfbe.png)

@mrinalwadhwa it looks like the order here is to blame. I'll take a look at the configuration. `clean` probably doesn't even need to run at all.

**Comment by mrinalwadhwa** [comment]
that's probably it, should be Lint, Build, Test, Clean
running clean ensures that the clean task is not broken for some reason.
