### ISSUE TITLE
generated bindings.rs causes uncommitted changes

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#532]
I started with no local changes in git.

from the root of the repo, I ran

```
./gradlew clean
./gradlew build
```

This updated the following file:
```
implementations/rust/c/bindings/src/bindings.rs
```

This should not happen, build shouldn't create uncommitted changes.

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa despite my [comment](https://github.com/ockam-network/ockam/pull/509#discussion_r504630800) "c/generate_bindings" target made it to default_members list of Cargo.toml. This is why we have that problems. @mikelodder7 could you please fix that?

**Comment by nilslice** [comment]
@mrinalwadhwa @SanjoDeundiak, I have some code that will insert the manual file changes (described in Sanjo's README) as part of the codegen step. I think it's worth adding in so that this doesn't become a bigger problem if others contribute. I'll get a PR going and we can discuss further.

**Comment by SanjoDeundiak** [comment]
@nilslice anyways, I'm not sure we want to regenerate bindings by default when running cargo build.

**Comment by mrinalwadhwa** [comment]
We should fix this before we release, it feels like a source of non determinism to me.
I agree with @SanjoDeundiak on not wanting bindgen happening on every build,
