### ISSUE TITLE
Rust default vault encryption test panics occasionally

### ISSUE THREAD

**Issue by SanjoDeundiak** [ockam-network/ockam#555]
Sometimes test run fails
thread 'software::tests::encryption' panicked at 'assertion failed: res.is_err()', vault/src/software/mod.rs:815:9
test software::tests::encryption ... FAILED

**Comment by mrinalwadhwa** [comment]
We saw this again https://github.com/ockam-network/ockam/runs/1779559344#step:8:646

**Comment by mrinalwadhwa** [comment]
Log of the failed run
[logs_5272.zip](https://github.com/ockam-network/ockam/files/5883384/logs_5272.zip)

**Comment by SanjoDeundiak** [comment]
Fixed
