### ISSUE TITLE
(Rust) re-use provided --identity-name key in ockamd

### ISSUE THREAD

**Issue by nilslice** [ockam-network/ockam#572]
The `--identity-name` CLI arg should define the key context that holds the target secret for `ockamd` to use at startup. 

If the key doesn't exist, `ockamd` should generate a new one, assuming that this is the first time it is run on a machine. If the key does exist, use it. 

Additionally, the filename of the stored key on disk needs to be updated to have the `.key` suffix as per the demo.

**Comment by robinbudd** [comment]
@nilslice can we close this?
