### ISSUE TITLE
file vault tests fail / don't clean temp files

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#616]
The elixir file vault tests
https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam_vault_software/test/vault_software_test.exs#L19

Fail when trying to create a vault at `/tmp`
And leave behind temporary files in the source code directory.

The should use `System.tmp_dir` instead https://hexdocs.pm/elixir/System.html#tmp_dir/0

**Comment by nilslice** [comment]
These worked last week before they were merged in. They actually fail in CI?

I agree we should change this to use the tmp_dir function tho, assuming that is automatically cleaned up? If it just creates a random directory like some other language implementations do, we'll need to store that location in a var and clean up manually still.

**Comment by mrinalwadhwa** [comment]
don't fail in CI because the CI machine doesn't mind that the test is trying to create /tmp
my dev machine doesn't like that.
