### ISSUE TITLE
(Rust) update Channel naming to SecureChannel

### ISSUE THREAD

**Issue by nilslice** [ockam-network/ockam#629]
Elixir has changed this (or has had it all along), so Rust should follow-suit.

**Comment by mrinalwadhwa** [comment]
Thanks for logging this, I decided that this communicated the intent better in APIs

**Comment by nilslice** [comment]
Fully agree -- it's been on the team's radar, but we'll get it sorted in the next mile for sure.

**Comment by niklaslong** [comment]
Stumbled upon this shortly after looking through some of the code, seems like this has been [resolved](https://github.com/ockam-network/ockam/commit/58c7ca5720dd232b9861f3918b71744929dba752).

**Comment by mrinalwadhwa** [comment]
Thanks @niklaslong 🙏 
Yes it has been, closing.
