### ISSUE TITLE
Design - Layer 2

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#668]
- [ ] Parts in yellow
- [x] Okta integration as the context 
- [x] Truck Example

![Screen Shot 2020-11-24 at 10 47 13 AM](https://user-images.githubusercontent.com/159583/100138150-6a3c7b80-2e42-11eb-81ee-1e6b1a312e54.png)

**Comment by mikelodder7** [comment]
[Trust Protocol](https://docs.google.com/document/d/1DXCTopVVW-MVoRYnEPqzri0D_xJvirk-5uq9nHENyYY/edit?usp=sharing)
