### ISSUE TITLE
Vault - Expand AES GCM 128 test cases

### ISSUE THREAD

**Issue by mtm0183** [ockam-network/ockam#74]
Need to investigate more test cases for AES GCM 128 to place in common vault tests.

**Comment by mrinalwadhwa** [comment]
https://github.com/google/wycheproof/blob/master/testvectors/aes_gcm_test.json

**Comment by mrinalwadhwa** [comment]
https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/mac/gcmtestvectors.zip
https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/mac/gcmvs.pdf
