### ISSUE TITLE
Vault - Accept non-null pointer with 0 length for encrypt/decrypt

### ISSUE THREAD

**Issue by robinbudd** [ockam-network/ockam#77]
## Expected Behavior
ockam_vault_aes_gcm_encrypt and ockam_vault_aes_gcm_decrypt should accept a non-NULL pointer to the en-/de-crypt buffer, with 0 length. As it is, the user must special-case the calls whenever a 0-length payload is submitted.

## Actual Behavior
The functions fail if length is 0 but pointer is not NULL

## Environment

- Ockam Version:
- Operating System:

**Comment by mtm0183** [comment]
@robinbudd Is this still an issue that needs reviewing?
