### ISSUE TITLE
ockam_node_attribute macro should validate input argument

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#793]

**Comment by gabhijit** [comment]
This would involve making sure that the number of inputs is one (already handled) and the type of the input is `ockam::Context` is that right? 

Also, if the input looks something like - 
```rust
#[ockam::node]
fn main(ctx: ockam::Context) {
// ...
}
``` 
Correctly capturing the name `ctx` above in place of current hard coded `context`. 

Is that right? I can give it a try.

**Comment by mrinalwadhwa** [comment]
Hi @gabhijit 👋 

Thank you for taking this up 🙏.

Yes, both those points makes sense.

There are some trybuild tests for the macro here which may be helpful as you tweak it.
https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam/tests  

@spacekookie may have some more thoughts/suggestions.

Cheers!

**Comment by mrinalwadhwa** [comment]
Also, before you send any changes, could you accept our CLA.

Read the CLA at
https://www.ockam.io/learn/how-to-guides/contributing/cla/

To accept the CLA please send a different PR to our contributors repo indicating that you accept the CLA by adding your Git/Github details in a row at the end of the CONTRIBUTORS.csv file:
https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv

Looking forward to merging your first contribution!! ❤️

**Comment by gabhijit** [comment]
@mrinalwadhwa Sure, I will be working on this over the weekend. 

Will send a PR for signing the CLA in the meanwhile.

**Comment by gabhijit** [comment]
In addition to the above validations, I am performing following additional validation -  Passed argument is used inside the function. Not sure whether this is required one, but I believe it doesn't make a lot of sense to use the function where passed argument is not used as `ockam::Context`.

**Comment by mrinalwadhwa** [comment]
Thanks @gabhijit that's a great idea 👍

**Comment by spacekookie** [comment]
I think we can close this issue for now.

The input validation is working pretty well (checking that there is a parameter, that it's the right type, and that the function is async). Because the macro now wraps the user function in a new main function, capturing the name of the parameter also isn't relevant anymore which makes things nice and simple for us.
