### ISSUE TITLE
Example - Node and Workers

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#950]
HELLO NODE AND WORKERS
---

Create a local Ockam Node - A
  - Create a local "echoer" Worker on A
  - Send the local "echoer" Worker a message
  - Receive a reply from the local "echoer"

**Comment by mrinalwadhwa** [comment]
@spacekookie could you post the simplest possible code snippet to do there here.

**Comment by mrinalwadhwa** [comment]
I think this should be something close to
https://github.com/ockam-network/ockam/blob/develop/implementations/rust/examples/worker/examples/worker_get_reply.rs

**Comment by spacekookie** [comment]
The simplest example I could come up with is

```rust
use ockam::{Context, Result, Worker};

struct Echoer;

impl Worker for Echoer {
    type Message = String;
    type Context = Context;

    fn handle_message(&mut self, ctx: &mut Context, msg: String) -> Result<()> {
        ctx.send_message("app", format!("{}", msg))
    }
}

fn main() {
    let (mut app, mut sys) = ockam::start_node();
    sys.execute(async move {
        app.start_worker("echo", Echoer).unwrap();

        let s = String::from("Hello ockam!");
        println!("Sending: {}", s);
        app.send_message("echo", s).unwrap();

        let reply = app.receive::<String>().unwrap();
        println!("Reply: {}", reply);

        app.stop().unwrap();
    })
    .unwrap();
}
```

**Comment by spacekookie** [comment]
A suggestion here: the future given to `execute` should return `Result<()>` so that users can `?` on the API calls. This will cut-down a lot of clutter

**Comment by mrinalwadhwa** [comment]
I didn't try to make this run, but what do you think of the below suggestions based on your code above. If you like it, could you try to get the working code close to this

```rust
use ockam::{Context, Result, Worker};

struct Echoer;

impl Worker for Echoer {
    type Message = String;
    type Context = Context;

    fn handle_message(&mut self, context: &mut Context, message: String) -> Result<()> {
        context.send_message("app", format!("{}", message))
    }
}

#[ockam::node]
async fn main(context: Context) {
    context.start_worker("echoer", Echoer)?;

    let message = String::from("Hello Ockam!");
    context.send_message("echoer", message)?;

    let reply = context.receive_message::<String>()?;
    println!("Reply: {}", reply);

    context.stop_node()?;
}
```

**Comment by spacekookie** [comment]
Yea this looks very nice. And getting `ockam_node_attribute` to expect the return value of the function to be `Result<()>` should be pretty easy. We may want to make it conditional based on what the user declares as a signature actually.

Also there needs to be an `Ok(())` on the last line (or remove the `?;`)

I'll post a PR about this in a bit.

**Comment by spacekookie** [comment]
So actually, the current `ockam_node_attribute` can already deal with `-> Result<()>` return values because the user code is wrapped in a new function, and the return type is passed through the executor.

Which means the example would look as follows:

```rust
use ockam::{Context, Result, Worker};

struct Echoer;

impl Worker for Echoer {
    type Message = String;
    type Context = Context;

    fn handle_message(&mut self, ctx: &mut Context, msg: String) -> Result<()> {
        ctx.send_message("app", format!("{}", msg))
    }
}

#[ockam::node]
async fn main() -> Result<()> {
    app.start_worker("echoer", Echoer).unwrap();

    let msg = String::from("Hello ockam!");
    app.send_message("echoer", s)?;

    let reply = app.receive::<String>()?;
    println!("Reply: {}", reply);

    app.stop()
}
```

The alternative is that the wrapped user function _always_ returns `Result<()>`, but then users may encounter errors about not returning a Result from the function with no clear indicator as to why they even should.

**Comment by spacekookie** [comment]
Minor thing we need to merge for this example to work: https://github.com/ockam-network/ockam/pull/973

(makes` app.receive::<String>()?` work)

**Comment by jared-s** [comment]
Thank you! I'll merge #973 next

**Comment by mrinalwadhwa** [comment]
@spacekookie The above looks great 👍

**Comment by jared-s** [comment]
I have staged the example https://github.com/ockam-network/ockam/blob/jared/ockam_examples/implementations/rust/ockam/ockam_examples/examples/guide_01_workers.rs

**Comment by jared-s** [comment]
https://ockamio2develop.z6.web.core.windows.net/learn/rust/01_workers

**Comment by spacekookie** [comment]
@jared-s the example looks good. A little bit of feedback from my end:

- It might be helpful to explicitly say that the user's `main` will be wrapped in a new `fn main()`. That might not be relevant immediately but still come up in stack traces
- I'd rename the `context` parameter in `async fn main(...)` to `ctx` to be in-line with the parameter name in the message handler.
- The code to receive a message is too indented

**Comment by jared-s** [comment]
Awesome thanks for the feedback @spacekookie I'll get these edits in!
