### ISSUE TITLE
Hub - Forwarding Service

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#962]

**Comment by mrinalwadhwa** [comment]
Required for #952

**Comment by mrinalwadhwa** [comment]
Forwarding Service is merged into develop and works with the UDP transport. Here's a test:

Start `iex` in the hub app:
```bash
cd implementations/elixir/ockam/ockam_hub
iex -S mix
```

Start UDP transport:
```elixir
{:ok, address} = Ockam.Transport.UDP.create_listener [port: 5000, route_outgoing: true]
```

Start `iex` in the ockam app:
```bash
cd implementations/elixir/ockam/ockam
iex -S mix
```

```
mix run --no-halt b.exs
```

```elixir
# b.exs

alias Ockam.Transport.UDPAddress
{:ok, address} = Ockam.Transport.UDP.create_listener [port: 6000, route_outgoing: true]

defmodule EchoService do
  use Ockam.Worker

  alias Ockam.Message

  @impl true
  def setup(_options, state) do
    state = Map.put(state, :registered, false)
    {:ok, state}
  end

  @impl true
  def handle_message(message, %{ registered: false } = state) do
    forwading_address = Message.payload(message)
    IO.puts("FORWADING ADDRESS: #{inspect({forwading_address, state})}")
    state = Map.put(state, :registered, true)
    {:ok, state}
  end

  @impl true
  def handle_message(message, state) do
    reply = %{
      onward_route: Message.return_route(message),
      return_route: [state.address],
      payload: Message.payload(message)
    }

    IO.puts("MESSAGE: #{inspect(message)}\nREPLY: #{inspect(reply)}")
    Router.route(reply)

    {:ok, state}
  end
end

EchoService.create(address: "echo_service")

route_to_node_running_forwading_service = [%UDPAddress{ip: {127, 0, 0, 1}, port: 5000}]
forwarding_service_register_request = %{
  onward_route: route_to_node_running_forwading_service ++ ["forwarding_service"],
  return_route: ["echo_service"],
  payload: "register"
}

Ockam.Router.route(forwarding_service_register_request)
```

This will print a forwarding address, copy it and pass it as first argument fo `a.exs`
```
mix run --no-halt a.exs 30a9f31d
```

```elixir
# a.exs

[forwading_address_of_echo_service_on_b | _] = System.argv()

alias Ockam.Transport.UDPAddress
{:ok, address} = Ockam.Transport.UDP.create_listener [port: 3000, route_outgoing: true]

defmodule Printer do
  use Ockam.Worker

  @impl true
  def handle_message(message, state) do
    IO.inspect(message, label: "printer")
    {:ok, state}
  end
end

Printer.create(address: "printer")

route_to_node_running_forwading_service = [%UDPAddress{ip: {127, 0, 0, 1}, port: 5000}]
message = %{
  onward_route: route_to_node_running_forwading_service ++ [forwading_address_of_echo_service_on_b],
  return_route: ["printer"],
  payload: "hello"
}

Ockam.Router.route(message)

```

**Comment by mrinalwadhwa** [comment]
@mjc this should work the same over TCP when we have return routes working.

**Comment by mrinalwadhwa** [comment]
The current naive forwarding service protocol is,
1. any message sent to the "forwarding service" is treated as a request to forward
2. payload of the message is ignored
3. return_route of the message is remembered as the forwarding_route
4. a forwarding address is sent as the payload of the reply

**Comment by hairyhum** [comment]
Updated in https://github.com/ockam-network/ockam/pull/1106
Step 4: forwarding address sent as a part of  the return_route in the reply

@mrinalwadhwa I have a question about step 3 now: why are messages forwarded to the return_route of the original message? That doesn't sound right, should it be the onward_route instead?

**Comment by mrinalwadhwa** [comment]
> I have a question about step 3 now: why are messages forwarded to the return_route of the original message? That doesn't sound right, should it be the onward_route instead?

I think it should be neither `return_route` nor `onward_route` in all steps 1 to 4 ... it should be `payload` in all cases.
The messages we exchange with the Forwarding Service should be separated from how we get those messages to and from the forwarding services.

With that idea, I think we need to design two messages in BARE schema that will be carried in payload of steps 1 to 4
1. RequestToForward
2. Reply To - the RequestToForward

**Comment by mrinalwadhwa** [comment]
If we make that separation, that I think it becomes easier/cleaner for someone to setup forwarding - on behalf of someone else.

**Comment by hairyhum** [comment]
@mrinalwadhwa right. But in a short term this might cause confusion as there is no way for a forwarding service to forward a message anywhere other than back to the sender. The remainder of the onward route is ignored.

**Comment by hairyhum** [comment]
Forwarding service was simplified to create an "alias" for a registered route and forward messages to this route from the alias.
The "mailbox" functionality is shifted to the stream service for now.
@mrinalwadhwa I believe this one may be closed and we can use learnings from this in the future registry service.
