### ISSUE TITLE
Build - lint for compliance with editroconfig

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#97]
Make the build fail if any file doesn't comply with editorconfig conventions.
```
vagrant ssh builder-debian -c "npx eclint@2.8.1 check implementations/c/source/ockam/transport"
```

**Comment by robinbudd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add linter to detect tabs in source files](https://trello.com/c/oBWFwLOr/7-add-linter-to-detect-tabs-in-source-files)

**Comment by mrinalwadhwa** [comment]
Added https://github.com/ockam-network/ockam/commit/e6fa60be8cb60b9aa3397ec4e8eca52f7d8d57c8
