### ISSUE TITLE
C - fix files that don't comply with editorconfig

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#99]
Multiple files in  `implementations/c` don't comply with editorconfig

```
vagrant ssh builder-debian -c "npx eclint@2.8.1 check implementations/c"
```

In  #97 we'll automate this test to make it pass we likely need to ignore some folders in editorconfig

```
[{third-party,_build}/**]
indent_style = ignore
indent_size = ignore
end_of_line = ignore
trim_trailing_whitespace = ignore
charset = ignore
```

Any folders starting with `.` are already ignored like `.build`

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa another option could be to integrate eclint on cmake level to either automatically fix sources or fail build. This way you avoid situations when you forget to run code style checks, then realise CI fails, you fix it and wait for another CI check... time consuming.
Another eclint alternative may be clang-format.
